# -*- coding: utf-8 -*-
"""thirdpartynews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15UB_0rFz9PiE-aXvxW7p-STXXp_RkLGi

Third-Party Breach News Classification — SLM Fine-Tuning Benchmark
3-Class Classification | LoRA/QLoRA | 4 Model Karsilastirma

Siniflar:

Class 0 — Ihlal Yok (genel siber guvenlik haberleri)
Class 1 — Dogrudan Ihlal (kurum dogrudan hedef alindi)
Class 2 — 3. Taraf Ihlali (vendor / supply-chain kaynakli)
Modeller: SmolLM2-360M | TinyLlama-1.1B | Qwen2.5-1.5B | Gemma 4 E2B
Runtime: Runtime → Change runtime type → T4 GPU → Save

1.Paket Kurulumu
"""

!pip install -q transformers==4.44.0 peft==0.12.0 accelerate==0.33.0 bitsandbytes==0.43.3
!pip install -q scikit-learn matplotlib seaborn datasets

import torch, sys
print(f"Python  : {sys.version.split()[0]}")
print(f"PyTorch : {torch.__version__}")
print(f"CUDA    : {torch.cuda.is_available()} | GPU: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'}")
print("Kurulum OK.")

!pip install -q numpy==2.0.0

"""2.Drive Baglantisi & Proje Dosyalaria"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')

import os, shutil

DRIVE_PATH = "/content/drive/MyDrive/third_party_breach_projects"
PROJECT    = "/content/project"

if os.path.exists(DRIVE_PATH):
    shutil.copytree(DRIVE_PATH, PROJECT, dirs_exist_ok=True)
    print("Drive'dan kopyalandi.")
else:
    os.makedirs(f"{PROJECT}/data", exist_ok=True)
    print("Drive yolu bulunamadi. Dosyalari manuel yukleyin.")

# %cd /content/project
!ls -la

"""3. Veri Hazirlama (3-Class)"""

import os

assert os.path.exists("/content/third_party_news.json"),    "third_party_news.json bulunamadi!"
assert os.path.exists("/content/not_third_party_news.json"), "not_third_party_news.json bulunamadi!"
print("Ham veri dosyalari mevcut.")

!python data_prep.py --show_samples

import pandas as pd, matplotlib.pyplot as plt, json
from collections import Counter

train_df = pd.read_csv("data/train.csv")
val_df   = pd.read_csv("data/val.csv")
test_df  = pd.read_csv("data/test.csv")

print(f"Train: {len(train_df)} | Val: {len(val_df)} | Test: {len(test_df)}")

LABEL_NAMES = {0: "Ihlal Yok", 1: "Dogrudan Ihlal", 2: "3. Taraf Ihlali"}

# Sinif dagilimi
cnt = Counter(train_df["label"])
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

bars = axes[0].bar(
    [LABEL_NAMES[l] for l in sorted(cnt)],
    [cnt[l] for l in sorted(cnt)],
    color=["#4C72B0", "#DD8452", "#55A868"]
)
axes[0].set_title("Sinif Dagilimi (Train)")
axes[0].set_ylabel("Ornek Sayisi")
for bar, (l, n) in zip(bars, sorted(cnt.items())):
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height()+2, str(n), ha='center', fontsize=10)

# Metin uzunlugu
train_df["char_len"] = train_df["text"].str.len()
axes[1].hist(train_df["char_len"], bins=40, color="steelblue", edgecolor="white")
axes[1].axvline(train_df["char_len"].mean(), color="red", linestyle="--",
                label=f"Ort: {train_df['char_len'].mean():.0f}")
axes[1].set_title("Metin Uzunlugu Dagilimi")
axes[1].set_xlabel("Karakter")
axes[1].legend()

plt.tight_layout()
os.makedirs("outputs", exist_ok=True)
plt.savefig("outputs/data_overview.png", dpi=120)
plt.show()
print("Grafik kaydedildi.")

"""CTI Analisti Etiket Dogrulama data_prep.py heuristik etiketleme yapiyor."""

# Class 1 (Dogrudan Ihlal) orneklerini incele
class1_df = train_df[train_df["label"] == 1].head(10)
for _, row in class1_df.iterrows():
    print(f"URL: {row.get('url', '-')}")
    print(f"Metin (ilk 200 kar): {row['text'][:200]}")
    print("-" * 60)

"""4. Model Konfigurasyonu"""

MODELS = {
    "smollm2"  : "HuggingFaceTB/SmolLM2-360M-Instruct",
    "tinyllama": "unsloth/tinyllama-chat-bnb-4bit",
    "qwen"     : "unsloth/qwen2.5-1.5b-instruct-bnb-4bit",
    "gemma"    : "unsloth/gemma-2-2b-it-bnb-4bit",
}

SELECTED_MODELS = ["smollm2", "tinyllama", "qwen","gemma"]
QUANTIZE        = {"tinyllama","qwen", "gemma"}                   # bu modeller 4-bit

print("Secili modeller:")
for k in SELECTED_MODELS:
    q = "(QLoRA 4-bit)" if k in QUANTIZE else "(LoRA FP16)"
    print(f"  {k:12s} {q}  ->  {MODELS[k]}")

"""5. Zero-Shot Baseline"""

!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps xformers trl peft accelerate bitsandbytes datasets

import json
from sklearn.model_selection import train_test_split

# Dosya adları (Uzantı yazmayı unuttuysan diye try-except ile yakalayacağız)
file_3rd_party = "third_party_news.json"
file_non_3rd_party = "not_third_party_news.json"

def load_data(filename, label):
    try:
        with open(filename, "r", encoding="utf-8") as f:
            data = json.load(f)
    except FileNotFoundError:
        # Uzantı eksiğini tolere et
        with open(filename + ".json", "r", encoding="utf-8") as f:
            data = json.load(f)

    formatted = []
    for item in data:
        formatted.append({
            "instruction": "You are a CTI expert. Classify the data breach: 1 (Internal Breach) or 2 (3rd Party Breach). Reply ONLY with the number 1 or 2.",
            "input": f"Title: {item.get('title', '')}\nContent: {item.get('content', '')[:1000]}",
            "output": str(label)
        })
    return formatted

print("1. Dosyalar okunuyor ve etiketleniyor...")
data_3rd = load_data(file_3rd_party, label=2)       # 3. Taraf -> Sınıf 2
data_non_3rd = load_data(file_non_3rd_party, label=1) # İç İhlal -> Sınıf 1

all_data = data_3rd + data_non_3rd
print(f"Toplam okunan veri: {len(all_data)} (3. Taraf: {len(data_3rd)}, İç İhlal: {len(data_non_3rd)})")

print("2. Veri Train/Val/Test olarak (Seed=42) bölünüyor...")
train_data, temp_test_data = train_test_split(all_data, test_size=0.20, random_state=42, stratify=[x["output"] for x in all_data])
val_data, test_data = train_test_split(temp_test_data, test_size=0.50, random_state=42, stratify=[x["output"] for x in temp_test_data])

def save_jsonl(data_list, filename):
    with open(filename, "w", encoding="utf-8") as f:
        for item in data_list:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

save_jsonl(train_data, "train.jsonl")
save_jsonl(val_data, "val.jsonl")
save_jsonl(test_data, "test.jsonl")

print("3. İŞLEM TAMAM! test.jsonl dosyası oluşturuldu, teste hazırız.")

import json
import time
import torch
from unsloth import FastLanguageModel
from tqdm.notebook import tqdm
from sklearn.metrics import accuracy_score, f1_score, classification_report

ZERO_SHOT_MODEL = "unsloth/tinyllama-chat-bnb-4bit"
print(f"Zero-shot modeli yukleniyor: {ZERO_SHOT_MODEL}")

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = ZERO_SHOT_MODEL,
    max_seq_length = 1024,
    dtype = None,
    load_in_4bit = True,
)
FastLanguageModel.for_inference(model)

print("Test verisi okunuyor...")
texts, labels = [], []
with open("test.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)
        texts.append(item["input"])
        labels.append(int(item["output"]))

alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
You are a CTI expert. Classify the data breach: 1 (Internal Breach) or 2 (3rd Party Breach). Reply ONLY with the number 1 or 2.

### Input:
{}

### Response:
"""

preds, t0 = [], time.time()
print(f"Test Başlıyor (n={len(texts)})...")

for text in tqdm(texts, desc="Çıkarım Yapılıyor"):
    prompt = alpaca_prompt.format(text)
    inputs = tokenizer([prompt], return_tensors = "pt").to("cuda")
    outputs = model.generate(**inputs, max_new_tokens = 2, use_cache = True)
    generated_text = tokenizer.batch_decode(outputs, skip_special_tokens = True)[0]

    response_part = generated_text.split("### Response:\n")[-1].strip()
    digits = [c for c in response_part if c in "12"]
    preds.append(int(digits[0]) if digits else 1)

elapsed = (time.time() - t0) * 1000 / len(texts)

print("\n--- Zero-Shot Sonuclari (TinyLlama) ---")
print(f"  Accuracy      : {accuracy_score(labels, preds):.4f}")
print(f"  Macro-F1      : {f1_score(labels, preds, average='macro', zero_division=0):.4f}")
print(f"  Weighted-F1   : {f1_score(labels, preds, average='weighted', zero_division=0):.4f}")
print(f"  Hız (ms/ornek): {elapsed:.1f}")

!pip install -U bitsandbytes triton

"""6. Fine-Tuning"""

import gc
import torch
from unsloth import FastLanguageModel
from trl import SFTTrainer
from transformers import TrainingArguments
from datasets import load_dataset
import os

os.makedirs("outputs", exist_ok=True)

# 1. Modele Özel Dinamik Yapılandırma (OOM Kalkanı)
MODEL_CONFIGS = {
    "smollm2":   {"name": "HuggingFaceTB/SmolLM2-360M-Instruct", "batch_size": 8, "quantize": False},
    "tinyllama": {"name": "unsloth/tinyllama-chat-bnb-4bit",     "batch_size": 4, "quantize": True},
    "qwen":      {"name": "unsloth/qwen2.5-1.5b-instruct-bnb-4bit", "batch_size": 2, "quantize": True},
    "gemma":     {"name": "unsloth/gemma-2-2b-it-bnb-4bit",      "batch_size": 2, "quantize": True} # En ağır model
}

# 2. Veri Seti Hazırlığı
dataset = load_dataset("json", data_files={"train": "train.jsonl"}, split="train")

alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{}

### Input:
{}

### Response:
{}"""

def format_prompts(examples):
    texts = []
    for inst, inp, out in zip(examples["instruction"], examples["input"], examples["output"]):
        # Modelin nerede duracağını bilmesi için EOS (End of Sequence) ekliyoruz
        texts.append(alpaca_prompt.format(inst, inp, out) + "<|endoftext|>")
    return {"text": texts}

train_dataset = dataset.map(format_prompts, batched=True)

# 3. Otomatik Eğitim Döngüsü
for model_key, config in MODEL_CONFIGS.items():
    print(f"\n{'='*70}")
    print(f"🚀 BAŞLIYOR: {model_key.upper()} | Batch Size: {config['batch_size']} | Quantize: {config['quantize']}")
    print(f"{'='*70}")

    # Modeli Yükle
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = config["name"],
        max_seq_length = 1024,
        dtype = None,
        load_in_4bit = config["quantize"]
    )

    # LoRA Adaptörlerini Tak
    model = FastLanguageModel.get_peft_model(
        model,
        r = 16,
        target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_alpha = 32, # Senin scriptindeki gibi 32 yaptık
        lora_dropout = 0,
        bias = "none",
        use_gradient_checkpointing = "unsloth",
        random_state = 42,
    )

    # Eğitimi Başlat
    trainer = SFTTrainer(
        model = model,
        tokenizer = tokenizer,
        train_dataset = train_dataset,
        dataset_text_field = "text",
        max_seq_length = 1024,
        dataset_num_proc = 2,
        args = TrainingArguments(
            per_device_train_batch_size = config["batch_size"], # Modele özel batch size
            gradient_accumulation_steps = 4,
            warmup_steps = 5,
            num_train_epochs = 5, # Senin komutundaki gibi 5 epoch
            learning_rate = 2e-4,
            fp16 = not torch.cuda.is_bf16_supported(),
            bf16 = torch.cuda.is_bf16_supported(),
            logging_steps = 10,
            optim = "adamw_8bit",
            seed = 42,
            output_dir = f"outputs/{model_key}",
        ),
    )

    trainer.train()

    # Kayıt İşlemi
    save_path = f"lora_{model_key}"
    model.save_pretrained(save_path)
    tokenizer.save_pretrained(save_path)
    print(f"✅ TAMAMLANDI VE KAYDEDİLDİ: {save_path}")

    # 4. KRİTİK ADIM: VRAM TEMİZLİĞİ (OOM YEMEMEK İÇİN)
    del model
    del tokenizer
    del trainer
    gc.collect()
    torch.cuda.empty_cache()
    print(f"🧹 VRAM Temizlendi, bir sonraki modele geçiliyor...\n")

print("🎉 4 MODELİN EĞİTİMİ BAŞARIYLA TAMAMLANDI!")

"""7. Test Seti Degerlendirme & Karsilastirma"""

import json
import time
import torch
import gc
import pandas as pd
from tqdm.notebook import tqdm
from sklearn.metrics import accuracy_score, f1_score
from unsloth import FastLanguageModel

# Kaydettiğimiz modellerin klasör isimleri
trained_models = ["lora_smollm2", "lora_tinyllama", "lora_qwen", "lora_gemma"]

print("1. Test verisi okunuyor...")
texts, labels = [], []
with open("test.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)
        texts.append(item["input"])
        labels.append(int(item["output"]))

alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
You are a CTI expert. Classify the data breach: 1 (Internal Breach) or 2 (3rd Party Breach). Reply ONLY with the number 1 or 2.

### Input:
{}

### Response:
"""

results = []

print(f"\n🏆 BÜYÜK FİNAL: {len(trained_models)} Modelin Test Seti (n={len(texts)}) Değerlendirmesi Başlıyor...\n")

for model_path in trained_models:
    print(f"🔄 [{model_path.upper()}] Yükleniyor...")

    # Modeli Yükle (4-bit inference)
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = model_path,
        max_seq_length = 1024,
        dtype = None,
        load_in_4bit = True,
    )
    FastLanguageModel.for_inference(model)

    preds = []
    t0 = time.time()

    for text in tqdm(texts, desc=f"Çıkarım ({model_path.replace('lora_','')})"):
        prompt = alpaca_prompt.format(text)
        inputs = tokenizer([prompt], return_tensors = "pt").to("cuda")

        outputs = model.generate(**inputs, max_new_tokens = 2, use_cache = True)
        generated_text = tokenizer.batch_decode(outputs, skip_special_tokens = True)[0]

        response_part = generated_text.split("### Response:\n")[-1].strip()
        digits = [c for c in response_part if c in "12"]
        preds.append(int(digits[0]) if digits else 1)

    elapsed = (time.time() - t0) * 1000 / len(texts)

    # Metrik Hesaplamaları
    acc = accuracy_score(labels, preds)
    mf1 = f1_score(labels, preds, average="macro", zero_division=0)
    wf1 = f1_score(labels, preds, average="weighted", zero_division=0)

    # Tablo için kaydet
    results.append({
        "Model": model_path.replace("lora_", "").upper(),
        "Accuracy": round(acc, 4),
        "Macro-F1": round(mf1, 4),
        "Weighted-F1": round(wf1, 4),
        "Hız (ms/örnek)": round(elapsed, 1)
    })

    # 🧹 OOM YEMEMEK İÇİN KRİTİK TEMİZLİK
    del model
    del tokenizer
    gc.collect()
    torch.cuda.empty_cache()

print("\n" + "="*60)
print(" 📊 FİNAL KARŞILAŞTIRMA TABLOSU (HOCA İÇİN)")
print("="*60)
df = pd.DataFrame(results)
print(df.to_string(index=False))
print("="*60)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Klasör kontrolü
os.makedirs("outputs", exist_ok=True)

# Çıkan güncel sonuçlarımız
data = [
    {"Model": "SMOLLM2", "Accuracy": 0.7500, "Macro-F1": 0.7402, "Weighted-F1": 0.7486, "Hız (ms/örnek)": 240.1},
    {"Model": "TINYLLAMA", "Accuracy": 1.0000, "Macro-F1": 1.0000, "Weighted-F1": 1.0000, "Hız (ms/örnek)": 173.8},
    {"Model": "QWEN", "Accuracy": 1.0000, "Macro-F1": 1.0000, "Weighted-F1": 1.0000, "Hız (ms/örnek)": 255.4},
    {"Model": "GEMMA", "Accuracy": 0.4167, "Macro-F1": 0.2941, "Weighted-F1": 0.2451, "Hız (ms/örnek)": 490.6}
]

df = pd.DataFrame(data)
df.to_csv("outputs/final_results.csv", index=False)
print("✅ final_results.csv diske kaydedildi.\n")

# Çizim kalitesini artırıyoruz
plt.rcParams['figure.dpi'] = 120

# --- GRAFİK 1: Model Karşılaştırma (Accuracy & F1) ---
plt.figure(figsize=(10, 6))
sns.set_theme(style="whitegrid")
df_melted = df.melt(id_vars="Model", value_vars=["Accuracy", "Weighted-F1"], var_name="Metrik", value_name="Skor")

ax = sns.barplot(x="Model", y="Skor", hue="Metrik", data=df_melted, palette="viridis")
plt.title("Model Performans Karşılaştırması (Test Seti)", fontsize=14, fontweight='bold')
plt.ylim(0, 1.15) # Etiketler sığsın diye tavanı biraz yükselttik
plt.ylabel("Skor (0.0 - 1.0)")

for p in ax.patches:
    ax.annotate(f"{p.get_height():.2f}", (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center', xytext=(0, 8), textcoords='offset points')

plt.legend(loc='lower right')
plt.tight_layout()
plt.savefig("outputs/model_comparison.png", dpi=300) # Önce diske kaydet
print("--- Model Performans Karşılaştırması ---")
plt.show() # Sonra Colab ekranına bas
plt.close()

# --- GRAFİK 2: Verimlilik Grafiği (F1 vs Inference Hızı) ---
plt.figure(figsize=(9, 6))
sns.scatterplot(data=df, x="Hız (ms/örnek)", y="Weighted-F1", hue="Model", s=250, palette="deep", edgecolor="black")

# Noktalara model isimlerini hizalı yaz
for i in range(df.shape[0]):
    plt.text(df["Hız (ms/örnek)"][i] + 5, df["Weighted-F1"][i], df["Model"][i],
             horizontalalignment='left', size='medium', color='black', weight='semibold')

plt.title("Verimlilik Analizi: Hız vs Performans", fontsize=14, fontweight='bold')
plt.xlabel("İnference Süresi (ms) - Daha düşük daha iyi")
plt.ylabel("Weighted-F1 Skoru - Daha yüksek daha iyi")
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.savefig("outputs/efficiency_plot.png", dpi=300) # Önce diske kaydet
print("\n--- Verimlilik Analizi ---")
plt.show() # Sonra Colab ekranına bas
plt.close()

"""8. Hata Analizi (CTI Analisti Perspektifi)"""

import json
import torch
from unsloth import FastLanguageModel
from tqdm.notebook import tqdm
import gc

# 1. Hata analizi için hata yapmış bir modeli seçiyoruz (TinyLlama %100 yaptığı için ondan hata çıkmaz)
ERROR_ANALYSIS_MODEL = "lora_smollm2"

print(f"🔍 CTI Hata Analizi Başlıyor. Model: {ERROR_ANALYSIS_MODEL.upper()}")

# 2. Modeli Yükle (4-bit inference modu)
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = ERROR_ANALYSIS_MODEL,
    max_seq_length = 1024,
    dtype = None,
    load_in_4bit = True,
)
FastLanguageModel.for_inference(model)

# 3. Test verisini oku
texts, true_labels = [], []
with open("test.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)
        texts.append(item["input"])
        true_labels.append(int(item["output"]))

alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
You are a CTI expert. Classify the data breach: 1 (Internal Breach) or 2 (3rd Party Breach). Reply ONLY with the number 1 or 2.

### Input:
{}

### Response:
"""

errors = []
class_names = {1: "İç İhlal (1)", 2: "3. Taraf İhlali (2)"}

# 4. Çıkarım ve Hata Avı
for idx, (text, true_label) in enumerate(tqdm(zip(texts, true_labels), total=len(texts), desc="Hatalar Aranıyor")):
    prompt = alpaca_prompt.format(text)
    inputs = tokenizer([prompt], return_tensors = "pt").to("cuda")

    outputs = model.generate(**inputs, max_new_tokens = 2, use_cache = True)
    generated_text = tokenizer.batch_decode(outputs, skip_special_tokens = True)[0]

    response_part = generated_text.split("### Response:\n")[-1].strip()
    digits = [c for c in response_part if c in "12"]
    pred_label = int(digits[0]) if digits else 1 # Hata yaparsa default 1

    # EĞER TAHMİN YANLIŞSA KAYDET
    if pred_label != true_label:
        # Haberin başlığını ve ilk 250 karakterini temizleyerek alıyoruz
        clean_text = text.replace("Title: ", "").replace("Content: ", "").strip()
        errors.append({
            "idx": idx,
            "text_snippet": clean_text[:250],
            "true_name": class_names[true_label],
            "pred_name": class_names[pred_label]
        })

# 5. VRAM Temizliği (Her zaman önce temizlik!)
del model
del tokenizer
gc.collect()
torch.cuda.empty_cache()

# 6. Sonuçları Raporla
print(f"\n🚨 Toplam {len(errors)} hata bulundu.")
print("--- İlk 5 Yanlış Sınıflandırma (CTI Analisti Gözüyle) ---\n")

for e in errors[:5]:
    print(f"📍 İndeks [{e['idx']}] | Gerçek = {e['true_name']}  ❌  Tahmin = {e['pred_name']}")
    print(f"📝 Metin: {e['text_snippet']}...\n")
    print("-" * 75)

"""9. Sonuclari Drive'a Kaydet"""

import os
import shutil
import datetime
from google.colab import drive

# Google Drive bağlı değilse bağlayalım
if not os.path.exists("/content/drive"):
    drive.mount('/content/drive')

# Zaman damgası ve hedef klasör oluşturma
ts = datetime.datetime.now().strftime("%Y%m%d_%H%M")
save_dir = f"/content/drive/MyDrive/third_party_breach_results_{ts}"
os.makedirs(save_dir, exist_ok=True)

# Yeni yapıda ürettiğimiz güncel ve kritik dosyaların listesi
files_to_copy = [
    "outputs/final_results.csv",
    "outputs/model_comparison.png",
    "outputs/efficiency_plot.png",
    "outputs/tum_hatalar_analiz.txt", # Yeni detaylı hata raporumuz
    "train.jsonl",                    # Eğitilen veri seti
    "val.jsonl",                      # Doğrulama veri seti
    "test.jsonl"                      # Test veri seti
]

# Kopyalama işlemi
for fname in files_to_copy:
    if os.path.exists(fname):
        shutil.copy(fname, save_dir)

print(f"Tüm güncel sonuçlar ve veri setleri Drive'a yedeklendi:\n  {save_dir}")